steps:
- task: CmdLine@2
  displayName: 'Clean untagged docker images'
  inputs:
    script: |
      sudo docker rm $(sudo docker ps -a | grep Exited | awk '{print $1;}') || true
      sudo docker container prune -f
      sudo docker image prune -f
    workingDirectory: $(Build.BinariesDirectory)
  continueOnError: true
  condition: always()


- task: CmdLine@2
  displayName: 'Create models link'
  inputs:
    script: |
      ln -s /data/models models
    workingDirectory: $(Build.BinariesDirectory)  